=== AndiNurfadillaAli/Web-Service-/Tugas/Perhotelan/bin/perhotelan/perhotelan.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="Perhotelan">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Pembayaran"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Pembayaran">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="dataPengunjung"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="dataPengunjung">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nokmr" minOccurs="1"/>
                <xs:element ref="Jeniskmr"/>
                <xs:element ref="tarif"/>
                <xs:element ref="Nama"/>
                <xs:element ref="cekIN"/>
                <xs:element ref="cekOut"/>
            </xs:sequence>
            <xs:attribute name="status" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="nokmr" type="xs:integer"/>
    <xs:element name="Jeniskmr" type="xs:NCName"/>
    <xs:element name="tarif" type="xs:NCName"/>
    <xs:element name="Nama" type="xs:NCName"/>
    <xs:element name="cekIN" type="xs:NMTOKEN"/>
    <xs:element name="cekOut" type="xs:NMTOKEN"/>
</xs:schema>

=== AndiNurfadillaAli/Web-Service-/Tugas/Perhotelan/bin/perhotelan/perhotelan.xml
<?xml version="1.0" encoding="UTF-8"?>
<Perhotelan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="perhotelan.xsd">
	<Pembayaran>
		<dataPengunjung status="terisi">
			<nokmr>011</nokmr>
			<Jeniskmr>vip</Jeniskmr>
			<tarif>Rp.550000</tarif>
			<Nama>dilla</Nama>
			<cekIN>01-04-2017</cekIN>
			<cekOut>02-04-02017</cekOut>
		</dataPengunjung>
		<dataPengunjung status="terisi">
			<nokmr>012</nokmr>
			<Jeniskmr>vip</Jeniskmr>
			<tarif>Rp.300000</tarif>
			<Nama>widya</Nama>
			<cekIN>01-04-2017</cekIN>
			<cekOut>02-04-2017</cekOut>
		</dataPengunjung>
		<dataPengunjung status="terisi">
			<nokmr>013</nokmr>
			<Jeniskmr>vip</Jeniskmr>
			<tarif>Rp.450000</tarif>
			<Nama>wahid</Nama>
			<cekIN>01-04-2017</cekIN>
			<cekOut>02-04-2017</cekOut>
		</dataPengunjung>
		<dataPengunjung status="terisi">
			<nokmr>014</nokmr>
			<Jeniskmr>vip</Jeniskmr>
			<tarif>Rp.400000</tarif>
			<Nama>jalal</Nama>
			<cekIN>01-04-2017</cekIN>
			<cekOut>02-04-2017</cekOut>
		</dataPengunjung>
		<dataPengunjung status="terisi">
			<nokmr>015</nokmr>
			<Jeniskmr>vip</Jeniskmr>
			<tarif>Rp.500000</tarif>
			<Nama>jaya</Nama>
			<cekIN>01-04-2017</cekIN>
			<cekOut>02-04-2017</cekOut>
		</dataPengunjung>
	</Pembayaran>
</Perhotelan>
